name:  workflow for Deploy Preview
on:
  pull_request:
    types:
      - closed
      - synchronize
    branches:
      - preview
      
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
        - uses: actions/checkout@v2

        - name: Install dependencies
          run: npm install
          env: 
            SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
            COMMERCIAL_TEMPLATE_ID: ${{ secrets.COMMERCIAL_TEMPLATE_ID }} 
            CLIENT_TEMPLATE_ID: ${{ secrets.CLIENT_TEMPLATE_ID }}
            FROM_SEND_EMAIL_HOMOLOG: ${{ secrets.FROM_SEND_EMAIL_HOMOLOG }}
            TO_SEND_EMAIL_COMMERCIAL: ${{ secrets.TO_SEND_EMAIL_COMMERCIAL }}

        - name: Run Build
          run: npm run build

        - name: Deploy Appllication in BKT for Preview
          uses: reggionick/s3-deploy@v3
          with:
            folder: .next
            bucket: ${{ secrets.S3_BUCKET }}
            bucket-region: ${{ secrets.S3_BUCKET_REGION }}
            dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
            invalidation: /
            delete-removed: true
            no-cache: true
            private: true
      